CREATE TABLE eventsData (
    id INT IDENTITY(1,1) PRIMARY KEY,
    schedulerID NVARCHAR(255),
    startDate NVARCHAR(50),
    endDate NVARCHAR(50),
    duration INT,
    durationUnit NVARCHAR(255),
    cls NVARCHAR(255),
    name NVARCHAR(255),
    calendar NVARCHAR(255),
    direction NVARCHAR(255),
    manuallyScheduled BIT,
    unscheduled BIT,
    ignoreResourceCalendar BIT,
    percentDone DECIMAL(5,2),
    effort DECIMAL(10,2),
    effortUnit NVARCHAR(255),
    segments NVARCHAR(255),
    effortDriven BIT,
    schedulingMode NVARCHAR(255),
    constraintType NVARCHAR(255),
    constraintDate NVARCHAR(50),
    inactive BIT,
    delayFromParent NVARCHAR(255),
    exceptionDates NVARCHAR(255),
    allDay BIT,
    eventColor NVARCHAR(255),
    showInTimeline BIT,
    note NVARCHAR(MAX),
    preamble NVARCHAR(255),
    postamble NVARCHAR(255),
);