CREATE TABLE schedulersData (
    schedulerID VARCHAR(50) PRIMARY KEY,
    expanded BIT,
    hoursPerDay INT,
    daysPerWeek INT,
    daysPerMonth INT,
    calendar VARCHAR(50),
    startDate DATETIME,
    endDate DATETIME,
    duration INT,
    durationUnit VARCHAR(10),
    direction VARCHAR(10),
    manuallyScheduled BIT,
    unscheduled BIT,
    unspecifiedTimeIsWorking BIT,
    skipNonWorkingTimeWhenSchedulingManually BIT,
    skipNonWorkingTimeInDurationWhenSchedulingManually BIT,
    percentDone DECIMAL(5,2),
    dependenciesCalendar VARCHAR(50),
    autoCalculatePercentDoneForParentTasks BIT,
    startedTaskScheduling VARCHAR(20),
    addConstraintOnDateSet BIT,
    autoScheduleManualTasksOnSecondPass BIT,
    allowPostponedConflicts BIT,
    autoPostponedConflicts BIT,
    autoMergeAdjacentSegments BIT
)